/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package syllabustracker;

import org.junit.Test;


public class MainAppTest {
    @Test public void appHasAGreeting() {
        MainApp classUnderTest = new MainApp();
    }
}
